<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\CustomerWithdraw;

class CustomerWithdrawController extends ApiController
{
	//
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new CustomerWithdraw($attributes);
	}

	public function index(Request $request, $conditionCall = null, $dataHandle = null)
    {
        return parent::index($request, $conditionCall, function ($entities){
            foreach ($entities as $entity){
                $entity->status_name = $entity->status();
            }
        }); // TODO: Change the autogenerated stub
    }

    public function store(Request $request)
    {
        $data = $request->except('token');

        if (empty($data['amt'])){
            return $this->fail('请输入提现金额');
        }

        $customer = $this->request->customer;
        $entity = $this->newEntity([
            'customer_id' => $customer->id,
            'amt' => $data['amt'],
            'status' => 1,
        ]);
        $entity->save();

        return $this->success($entity,'您已成功提交提现申请，我们将会在4-5个工作日内处理您的提现申请');
//        return parent::store($request); // TODO: Change the autogenerated stub
    }
}