<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\CustomerWithdraw;

class CustomerWithdrawController extends ApiController
{
	//
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new CustomerWithdraw($attributes);
	}

	public function index(Request $request, $conditionCall = null, $dataHandle = null)
    {
        return parent::index($request, $conditionCall, function ($entities){
            foreach ($entities as $entity){
                $entity->status_name = $entity->status();
            }
        }); // TODO: Change the autogenerated stub
    }

    public function store(Request $request)
    {
        $data = $request->except('token');

        if (empty($data['amt'])){
            return $this->fail('请输入提现金额');
        }

        $customer = $this->request->customer;
        $account = $customer->account;

        if ($account->deposit < $data['amt'] ){
            return $this->fail('您当前可提现押金余额不足，当前可提现押金为'.$account->deposit.'元');
        }

        $withing_amt = CustomerWithdraw::where('customer_id',$customer->id)->where('status',CustomerWithdraw::STATUS_INIT)->sum('amt');

        if ($account->deposit < $withing_amt ){
            return $this->fail('您当前已有'.$withing_amt.'元押金正在申请提现中。');
        }

        $entity = $this->newEntity([
            'customer_id' => $customer->id,
            'amt' => $data['amt'],
            'status' => 1,
            'sn' => 'TX'.sprintf("%05d", $customer->id) .date('YmdHis')
        ]);
        $entity->save();

        return $this->success($entity,'您已成功提交提现申请，我们将会在4-5个工作日内处理您的提现申请');
//        return parent::store($request); // TODO: Change the autogenerated stub
    }
}