<?php

namespace App\Http\Controllers\Api;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\Help;

class HelpController extends ApiController
{
	//
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new Help($attributes);
	}

	public function fillQueryForIndex(Request $request, Builder &$query)
    {
        parent::fillQueryForIndex($request, $query); // TODO: Change the autogenerated stub
        $query->select(['id', 'name', 'sort']);
    }
}