<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Api\ApiController;
use App\Models\Site;

class SiteController extends ApiController
{
    //
    public function newEntity(array $attributes = [])
    {
        // TODO: Implement newEntity() method.
        return new Site($attributes);
    }

    public function index(Request $request, $conditionCall = null, $dataHandleCall = null)
    {
        return parent::index($request, function ($query) {
            $query->where('longitude', '!=', '')
                ->where('latitude', '!=', '');
        }, $dataHandleCall); // TODO: Change the autogenerated stub
    }
}