<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Events\ModelCreatedEvent;
use App\Events\ModelUpdatedEvent;
use App\Events\ModelDeletedEvent;

class BaseModel extends Model
{
    //
	protected $guarded=['id'];
	protected $dateFormat='Y-m-d H:i:s';

	public function __construct(array $attributes = []){
		parent::__construct($attributes);
	}

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($model){
            event(new ModelCreatedEvent($model));
        });
        static::deleted(function ($model){
            event(new ModelDeletedEvent($model));
        });
        static::updated(function ($model){
            event(new ModelUpdatedEvent($model));
        });
    }
}
