<?php

namespace App\Models;

use App\Events\ModelCreatedEvent;
use App\Events\ModelUpdatedEvent;
use App\Events\PaymentEvent;
use Illuminate\Database\Eloquent\Model;
use App\Models\BaseModel;

/**
 * model description
 * Class CustomerHire
 * @package  App\Models
 *
 * @author  xrs
 * @SWG\Model(id="CustomerHire")
 * @SWG\Property(name="created_at", type="string", description="")
 * @SWG\Property(name="creator_id", type="integer", description="创建用户id")
 * @SWG\Property(name="customer_id", type="integer", description="customer id")
 * @SWG\Property(name="deleted_at", type="string", description="")
 * @SWG\Property(name="expired_at", type="string", description="到期时间")
 * @SWG\Property(name="expire_day", type="integer", description="有效期（天）")
 * @SWG\Property(name="hire_amt", type="number", description="租借费用")
 * @SWG\Property(name="hire_at", type="string", description="借伞时间")
 * @SWG\Property(name="hire_day", type="integer", description="租用时长")
 * @SWG\Property(name="hire_equipment_id", type="integer", description="equipments id 借伞设备id")
 * @SWG\Property(name="hire_site_id", type="integer", description="sites id 借伞网点id")
 * @SWG\Property(name="id", type="integer", description="")
 * @SWG\Property(name="margin_amt", type="number", description="缴纳的保证金")
 * @SWG\Property(name="modifier_id", type="integer", description="修改用户id")
 * @SWG\Property(name="return_at", type="string", description="还伞时间")
 * @SWG\Property(name="return_equipment_id", type="integer", description="equipments id 还伞设备id")
 * @SWG\Property(name="return_site_id", type="integer", description="sites id 还伞网点id")
 * @SWG\Property(name="status", type="integer", description="状态(1-初始(未支付押金)，2-租借中, 3-还伞完毕，待支付租金 4-已完成, 5-逾期未归还)")
 * @SWG\Property(name="umbrella_id", type="integer", description="umbrellas id")
 * @SWG\Property(name="updated_at", type="string", description="")
 */
class CustomerHire extends BaseModel
{
    /**
     * 租借状态：1-初始(未支付押金)
     */
    const STATUS_INIT = 1;
    /**
     * 租借状态：2-租借中
     */
    const STATUS_HIRING = 2;
    /**
     * 租借状态：3-还伞完毕，待支付租金
     */
    const STATUS_PAYING = 3;
    /**
     * 租借状态：4-已完成
     */
    const STATUS_COMPLETE = 4;
    /**
     * 租借状态： 5-逾期未归还
     */
    const STATUS_EXPIRED = 5;

    //
    protected $table = 'customer_hires';
    protected $guarded = ['id'];

    public $validateRules = [
//        'id' => 'required',
    ];

    public $validateMessages = [
//        'id.required' => "id不能为空",
    ];

    public function payment()
    {
        return $this->morphOne(User::class, 'reference');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($model) {
            event(new ModelCreatedEvent($model));
        });
        static::updated(function ($model) {
            event(new ModelUpdatedEvent($model));

            $payment = new CustomerPayment();
            switch ($model->status) {

                case CustomerHire::STATUS_COMPLETE: { //完成租借 退还押金
                    $payment->createPayment([
                        'type' => CustomerPayment::TYPE_INT_DEPOSIT_BACK,
                        'amt' => $model->deposit_amt,
                        'customer_id' => $model->customer_id,
                        'reference_id' => $model->id,
                        'reference_type' => 'App\Models\CustomerHire',
                    ], CustomerPayment::STATUS_SUCCESS);

                    break ;
                }
                default : {
                    break ;
                }
            }

        });
    }

    public function status()
    {
        switch ($this->status) {
            case 1: {
                return '初始(未支付押金)';
            }
            case 2: {
                return '租借中';
            }
            case 3: {
                return '还伞完毕，待支付租金';
            }
            case 4: {
                return '已完成';
            }
            case 5: {
                return '逾期未归还';
            }
        }
    }

}
