<?php

namespace App\Models;

use App\Events\ModelCreatedEvent;
use App\Events\ModelUpdatedEvent;
use App\Events\PaymentEvent;
use Illuminate\Database\Eloquent\Model;
use App\Models\BaseModel;

/**
 * model description
 * Class CustomerHire
 * @package  App\Models
 *
 * @author  xrs
 * @SWG\Model(id="CustomerHire")
 * @SWG\Property(name="created_at", type="string", description="")
 * @SWG\Property(name="creator_id", type="integer", description="创建用户id")
 * @SWG\Property(name="customer_id", type="integer", description="customer id")
 * @SWG\Property(name="deleted_at", type="string", description="")
 * @SWG\Property(name="expired_at", type="string", description="到期时间")
 * @SWG\Property(name="expire_day", type="integer", description="有效期（天）")
 * @SWG\Property(name="hire_amt", type="number", description="租借费用")
 * @SWG\Property(name="hire_at", type="string", description="借伞时间")
 * @SWG\Property(name="hire_day", type="integer", description="租用时长")
 * @SWG\Property(name="hire_equipment_id", type="integer", description="equipments id 借伞设备id")
 * @SWG\Property(name="hire_site_id", type="integer", description="sites id 借伞网点id")
 * @SWG\Property(name="id", type="integer", description="")
 * @SWG\Property(name="margin_amt", type="number", description="缴纳的保证金")
 * @SWG\Property(name="modifier_id", type="integer", description="修改用户id")
 * @SWG\Property(name="return_at", type="string", description="还伞时间")
 * @SWG\Property(name="return_equipment_id", type="integer", description="equipments id 还伞设备id")
 * @SWG\Property(name="return_site_id", type="integer", description="sites id 还伞网点id")
 * @SWG\Property(name="status", type="integer", description="状态(1-初始，2-未拿伞租借失败，3-租借中, 4-还伞完毕，待支付租金 5-已完成, 6-逾期未归还)")
 * @SWG\Property(name="umbrella_id", type="integer", description="umbrellas id")
 * @SWG\Property(name="updated_at", type="string", description="")
 */
class CustomerHire extends BaseModel
{
	/**
	 * 租借状态：1-初始
	 */
	const STATUS_INIT = 1;
	/**
	 * 租借状态：2-未拿伞,租借失败
	 */
	const STATUS_FAIL = 2;
	/**
	 * 租借状态：3-租借中
	 */
	const STATUS_HIRING = 3;
	/**
	 * 租借状态：4-还伞完毕，待支付租金
	 */
	const STATUS_PAYING = 4;
	/**
	 * 租借状态：5-已完成
	 */
	const STATUS_COMPLETE = 5;
	/**
	 * 租借状态： 6-逾期未归还
	 */
	const STATUS_EXPIRED = 6;

    //
    protected $table = 'customer_hires';
    protected $guarded = ['id'];

    public $validateRules = [
        'id' => 'required',
    ];

    public $validateMessages = [
        'id.required' => "id不能为空",
    ];

    public function payment()
    {
        return $this->morphOne(User::class, 'reference');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($model) {
            event(new ModelCreatedEvent($model));
        });
        static::updated(function ($model) {
            event(new ModelUpdatedEvent($model));
            $payment = new CustomerPayment();
            $payment->createPayment([
                'type' => 4,
                'amt' => $model->deposit_amt,
                'customer_id' => $model->customer_id,
                'reference_id' => $model->id,
                'reference_type' => 'App\Models\CustomerHire',
            ],2);

        });
    }

    public function status(){
        switch ($this->status) {
            case 1: {
                return '租借中';
            }
            case 2: {
                return '待支付租金';
            }
            case 3: {
                return '已完成';
            }
            case 4: {
                return '逾期未归还';
            }
        }
    }

}
