<?php

namespace App\Providers;

use App\Models\Comment;
use App\Services\Sms\AliDaYuSms;
use App\Services\Sms\ISmsSvr;
use Illuminate\Support\ServiceProvider;
use App\Models\CustomerPayment;
use App\Models\CustomerHire;
use Illuminate\Database\Eloquent\Relations\Relation;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
	    Relation::morphMap([
		    'customer_payment' => CustomerPayment::class,
		    'customer_hire' => CustomerHire::class,
            'comment' => Comment::class,
	    ]);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

	public function provides()
	{
		return [
		]; // TODO: Change the autogenerated stub
	}
}
