<?php
namespace App\Http\Controllers\Admin;

use App\Models\Site;
use Illuminate\Http\Request;
use App\Http\Controllers\Admin\BaseController;
use App\Models\EquipmentLog;

class EquipmentLogController extends BaseController
{
    public function newEntity(array $attributes = [])
    {
        // TODO: Implement newEntity() method.
        return new EquipmentLog($attributes);
    }

    /**
     * Display a listing of the resource.
     *
     * @return  \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.equipment-log.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return  \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.equipment-log.create');
    }

    /**
     * Display the specified resource.
     *
     * @param    int $id
     * @return  \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entity = EquipmentLog::find($id);
        return view('admin.equipment-log.edit', ['entity' => $entity]);
    }

    /**
     * Display the specified resource.
     *
     * @param    int $id
     * @return  \Illuminate\Http\Response
     */
    public function show($id)
    {
        $entity = EquipmentLog::find($id);
        return view('admin.equipment-log.show', ['entity' => $entity]);
    }

    /**
     * @param  Request $request
     * @param  array $searchCols
     * @param  array $with
     * @param  null $conditionCall
     * @param  bool $all_columns
     * @return  \Illuminate\Http\JsonResponse
     */
    public function pagination(Request $request, $searchCols = [], $with = [], $conditionCall = null, $dataHandleCall = null, $all_columns = false)
    {
        $searchCols = [];
        return parent::pagination($request, $searchCols, $with, $conditionCall, $dataHandleCall, true);
    }

//    public function entityQuery()
//    {
//        $query = EquipmentLog::query();
//
//        $query->select(
//            'equipment_logs.id as id',
//            'equipment_logs.api_name',
//            'equipment_logs.code',
//            'equipment_logs.type',
//            'equipment_logs.content',
//            'equipment_logs.equipment_id',
//            'equipment_logs.site_id',
//            'equipment_logs.created_at',
//            'equipments.sn as equipments_sn',
//            'sites.name as site_name'
//        );
//        $query->leftJoin('equipments', function ($join) {
//            $join->on('equipments.id', '=', 'equipment_logs.equipment_id');
//        });
//
//        $query->leftJoin('sites', function ($join) {
//            $join->on('sites.id', '=', 'equipment_logs.site_id');
//        });
//        return $query; // TODO: Change the autogenerated stub
//    }

}
