<?php
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\BaseController;
use App\Models\Partner;
use Illuminate\Support\Facades\Hash;

class PartnerController extends BaseController
{
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new Partner($attributes);
	}

	/**
	* Display a listing of the resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function index()
	{
		//
		return view('admin.partner.index');
	}

	/**
	* Show the form for creating a new resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function create()
	{
		return view('admin.partner.create');
	}

	public function store(Request $request, $only = [], $extraFields = [], $redirect_url = null)
    {
        $data = $request->all();
        if(Partner::where('name',$data['name'])->count() > 0)
            return $this->fail('该经销商账号已存在');

        $extraFields['password'] = Hash::make($data['password']);
        $redirect_url = url('/admin/partner');

        return parent::store($request, $only, $extraFields, $redirect_url); // TODO: Change the autogenerated stub
    }

    /**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function edit($id)
	{
		$entity = Partner::find($id);
		return view('admin.partner.edit', ['entity' => $entity]);
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function show($id)
	{
		//
	}

	/**
	* @param  Request $request
	* @param  array $searchCols
	* @param  array $with
	* @param  null $conditionCall
	* @param  bool $all_columns
	* @return  \Illuminate\Http\JsonResponse
	*/
	public function pagination(Request $request, $searchCols = [], $with=[], $conditionCall = null, $dataHandleCall = null, $all_columns = false){
		$searchCols = ["address","full_name","linkman","mobile","name","password","remember_token"];
		return parent::pagination($request, $searchCols);
	}

	public function changeStatus($id){
	    $entity = Partner::find($id);

        $entity->status = $entity->status == 1 ? 2 : 1;
        $entity->save();

        return redirect(url('/admin/partner'));
    }

}
