<?php
namespace App\Http\Controllers\Admin;

use App\Models\Resource;
use Illuminate\Http\Request;
use App\Http\Controllers\Admin\BaseController;
use App\Models\Site;

class SiteController extends BaseController
{
	public function newEntity(array $attributes = [])
	{
		// TODO: Implement newEntity() method.
		return new Site($attributes);
	}

	/**
	* Display a listing of the resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function index()
	{
		//
		return view('admin.site.index');
	}

	/**
	* Show the form for creating a new resource.
	*
	* @return  \Illuminate\Http\Response
	*/
	public function create()
	{
		return view('admin.site.create');
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function edit($id)
	{
		$entity = Site::find($id);
		return view('admin.site.edit', ['entity' => $entity]);
	}

	/**
	* Display the specified resource.
	*
	* @param    int  $id
	* @return  \Illuminate\Http\Response
	*/
	public function show($id)
	{
		$entity = Site::find($id);
		return view('admin.site.show', ['entity' => $entity]);
	}

	/**
	* @param  Request $request
	* @param  array $searchCols
	* @param  array $with
	* @param  null $conditionCall
	* @param  bool $all_columns
	* @return  \Illuminate\Http\JsonResponse
	*/
	public function pagination(Request $request, $searchCols = [], $with=[], $conditionCall = null, $dataHandleCall = null, $all_columns = false){
		$searchCols = ["address","city","district","latitude","longitude","name","province"];
		return parent::pagination($request, $searchCols);
	}

	public function store(Request $request, $only = [], $extraFields = [], $redirect_url = null)
    {
//        $file = $request->file('photo_id');

        $resource = new Resource();
        if($request->hasFile('photo_id')){
            $res_id = $resource->createResource($request->file('photo_id'));
            $extraFields['photo_id'] = $res_id;
        }
        $redirect_url = '/admin/site';
        return parent::store($request, $only, $extraFields, $redirect_url); // TODO: Change the autogenerated stub
    }

    public function update(Request $request, $id, $only = [], $extraFields = [], $redirect_url = null)
    {
        $resource = new Resource();
        if($request->hasFile('photo_id')){
            $res_id = $resource->createResource($request->file('photo_id'));
            $extraFields['photo_id'] = $res_id;
        }
        $redirect_url = '/admin/site';
        return parent::update($request, $id, $only, $extraFields, $redirect_url); // TODO: Change the autogenerated stub
    }
}
